my_redshift_project:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "dbt-poc.cgjf9xzsnjp1.eu-north-1.redshift.amazonaws.com"
      user: "infra-admin"
      password: "RCNXIuhgci550%&"
      port: 5439
      dbname: "dev"
      schema: "dbt_analytics"  # The schema where dbt will build your table
